#!/bin/bash
# Check that cobbler-settings can enable/disable the auto-migration of the YAML

# Arrange
source ${SYSTESTS_PRELUDE} && prepare

set -x -e -o pipefail

# Act
cobbler-settings -c "$TEST_CONFIG" automigrate --enable

# Assert
exit 1
