#!/bin/bash
# Check that cobbler-settings can modify value from the YAML

# Arrange
source ${SYSTESTS_PRELUDE} && prepare

set -x -e -o pipefail

TEST_CONFIG="${tmp}/settings-list.yaml"
cat <<-END >$TEST_CONFIG
build_reporting_email:
  - 'root@localhost'
END

TEST_KEY=""
TEST_VALUE=""

# Act
cobbler-settings -c "$TEST_CONFIG" modify -k "$TEST_KEY" -v "$TEST_VALUE"

# Assert
grep "$TEST_KEY: $TEST_VALUE" $TEST_CONFIG
