#!/bin/bash
# Check that cobbler-settings can modify value from the YAML

# Arrange
source ${SYSTESTS_PRELUDE} && prepare

set -x -e -o pipefail

# Act
cobbler-settings -c "$TEST_CONFIG" modify -k "$TEST_KEY" -v "$TEST_VALUE"

# Assert
exit 1
