#!/bin/bash
# Check that cobbler-settings can modify value from the YAML

# Arrange
source ${SYSTESTS_PRELUDE} && prepare

set -x -e -o pipefail

TEST_CONFIG="${tmp}/settings-dict.yaml"
cat <<-END >$TEST_CONFIG
mgmt_parameters:
 from_cobbler: true
END

TEST_KEY=""
TEST_VALUE=""

# Act
cobbler-settings -c "$TEST_CONFIG" modify -k "$TEST_KEY" -v "$TEST_VALUE"

# Assert
grep "$TEST_KEY: $TEST_VALUE" $TEST_CONFIG
